---

- hosts: switches
  become: true
  gather_facts: no
  tasks: 
  
    - name: Apply the provided configuration
      cisco.ios.ios_hostname:
        config:
          hostname: S1
        state: merged

    - name: configuring login banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          Unauthorized Personels are Prohibited!
        state: present
   
    - name: configuring domain name
      cisco.ios.ios_system:
        domain_name: www.tip.edu.ph
        state: present

    - name: configuring line con 0
      cisco.ios.ios_config:
        lines:
        - password cisco
        - login
        - logging synchronous 
        parents: line console 0

    - name: configuring privilege exec mode password 
      cisco.ios.ios_config:
        lines: enable secret class

    - name: saving running config to startup config
      cisco.ios.ios_config:
        save_when: modified 
   
    # implementing security
    - name: configuring service password-encryption
      cisco.ios.ios_config:
        lines:
        - service password-encryption

    - name: Shutdown interfaces
      cisco.ios.ios_config:
        lines: 
          - shutdown
        parents: "interface {{ item }}"
      with_items:
        - Ethernet0/3
        - Ethernet1/0
        - Ethernet1/1
        - Ethernet1/2
        - Ethernet1/3
        - Ethernet2/0
        - Ethernet2/1
        - Ethernet2/2
        - Ethernet2/3
        - Ethernet3/0
        - Ethernet3/1
        - Ethernet3/2
        - Ethernet3/3

    # displaying current config
    - block:

      - name: checking hostname
        cisco.ios.ios_command:
          commands: show run 
        register: output_run

      - debug: 
          msg="{{ output_run }}"



